# Generated by Django 4.2 on 2025-02-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="change",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Сдача"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                verbose_name="Внесенная сумма",
            ),
            preserve_default=False,
        ),
    ]
