# Generated by Django 4.2 on 2025-02-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commerce", "0002_transaction_change_transaction_deposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("error", "Ошибка")],
                default=1,
                max_length=100,
                verbose_name="Статус транзакции",
            ),
            preserve_default=False,
        ),
    ]
